defaults:
  - _global  # Import global config settings
  - _self_  # Must include the settings from this file

trainer:
  input_dim: 10
  hidden_dim: 64
  num_classes: 3
  batch_size: 32  # Per-GPU batch size
  learning_rate: 1e-3
  num_epochs: 1000
  seed: 42

hydra:
  job:
    name: hydra_mlp-ddp
  searchpath:
    - pkg://configs  # Include configs from the configs package in the searchpath
