defaults:
  - _global  # Import global config settings
  - _self_  # Must include the settings from this file

trainer:
  model_name: distilbert-base-uncased
  dataset_name: ag_news
  num_labels: 4
  max_length: 256
  num_train_epochs: 2
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  learning_rate: 5e-5
  weight_decay: 0.01
  logging_steps: 50
  save_steps: 100  # Save every N steps, cktp number is incremental.
  eval_steps: 200
  save_total_limit: 2  # By default the latest and best checkpoint will always be kept.

hydra:
  job:
    name: hydra_txt-classifier
  searchpath:
    - pkg://configs  # Include configs from the configs package in the searchpath
